kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  VERSION: 0.0.1


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git
    commands:
      - echo $testparam

  - name: 改变
    image: ccr.ccs.tencentyun.com/dronestock/changelog
    settings:
      version: $${VERSION}

  - name: 提交
    image: ccr.ccs.tencentyun.com/dronestock/git
    settings:
      remote: git@github.com:dronestock/changelog.git
      key:
        from_secret: ssh_key_github

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      output:
        name: changelog

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/docker
    privileged: true
    volumes:
      - name: docker
        path: /var/lib/docker
    environment:
      PASSWORD_DOCKER:
        from_secret: token_docker
      PASSWORD_CCR:
        from_secret: password_tencentyun_ccr
    settings:
      repository: dronestock/changelog
      registries:
        - username: dronestock
          password: $${PASSWORD_DOCKER}
        - hostname: ccr.ccs.tencentyun.com
          username: "160290688"
          password: $${PASSWORD_CCR}
          required: true


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
  - name: docker
    host:
      path: /var/lib/cache/docker
